name: CI-CodeBuild 🚀

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: codebuild-ubuntu-small
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v2

      - name: ⎔ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: 📥 Download deps
        run: npm ci

      - name: 🧪 Run lint
        run: npm run lint

  build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
          - 20
        os: [codebuild-ubuntu-small]
        browser:
          - FirefoxHeadless
        include:
          - os: windows-latest
            node: 20
            browser: FirefoxHeadless

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout
        uses: actions/checkout@v2

      - name: ⎔ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: 📥 Download deps
        run: npm ci

      - name: Run coverage
        run: npm test

      - name: Setup firefox - install gtk3
        if: matrix.os == 'codebuild-ubuntu-small' && matrix.node == '20'
        run: |
          apt-add-repository -y "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner" \
            && apt-get update \
            && apt-get install -y -qq libgtk-3-0 libglib2.0-0 libdbus-glib-1-2 libdbus-1-3 libasound2

      - name: Setup firefox - install firefox browser
        if: matrix.os == 'codebuild-ubuntu-small' && matrix.node == '20'
        id: setup-firefox
        uses: browser-actions/setup-firefox@latest

      - name: Run browser tests
        if: matrix.node == 20
        run: npm run mocha-browser-test -- --browsers ${{ matrix.browser }}  --timeout 10000
        env:
          DISPLAY: :99.0

      - name: Coverage
        if: matrix.os == 'codebuild-ubuntu-small' && matrix.node == '20'
        run: npm run coverage && npx nyc report --reporter=lcov

      - name: Coveralls
        if: matrix.os == 'codebuild-ubuntu-small' && matrix.node == '20'
        uses: coverallsapp/github-action@1.1.3
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
